from __future__ import annotations

from collections import Counter


ALIGNMENT_REQUIREMENTS: list[dict[str, object]] = [
    {
        "requirement_key": "proposal_quasi_experimental_design",
        "arabic_label": "تصميم شبه تجريبي قبل/بعد",
        "technical_label": "Quasi-experimental before-after study design",
        "source_document_category": "research_proposal",
        "status": "implemented",
        "related_api_route": "/api/studies",
        "related_frontend_route": "study-management",
        "related_export_fields": ["study_phase", "study_group"],
        "notes": "Study protocol stores phase/group needed for before-after comparison.",
    },
    {
        "requirement_key": "proposal_control_experimental_groups",
        "arabic_label": "مجموعة ضابطة ومجموعة تجريبية",
        "technical_label": "Control versus experimental groups",
        "source_document_category": "research_proposal",
        "status": "implemented",
        "related_api_route": "/api/patients",
        "related_frontend_route": "patient-baseline",
        "related_export_fields": ["study_group"],
        "notes": "Patient records preserve the research group assignment.",
    },
    {
        "requirement_key": "proposal_demographic_clinical_data",
        "arabic_label": "البيانات الديموغرافية والسريرية",
        "technical_label": "Patient demographic and clinical context",
        "source_document_category": "research_proposal",
        "status": "implemented",
        "related_api_route": "/api/patients",
        "related_frontend_route": "patient-baseline",
        "related_export_fields": ["patient_code", "age", "gender", "education_level", "dry_weight_kg", "dialysis_start_date", "weekly_sessions_count", "comorbidities"],
        "notes": "Dataset excludes names and keeps anonymized patient codes.",
    },
    {
        "requirement_key": "proposal_digital_monitoring",
        "arabic_label": "المراقبة الرقمية NEWS2 / HD2-mNEWS",
        "technical_label": "Digital NEWS2 and HD2-mNEWS monitoring",
        "source_document_category": "research_proposal",
        "status": "implemented",
        "related_api_route": "/api/monitoring/measurements",
        "related_frontend_route": "intradialytic-monitoring",
        "related_export_fields": ["news2_total_score", "hd2_mnews_total_score", "hd2_risk_color"],
        "notes": "Standard NEWS2 remains available while HD2-mNEWS fields are persisted for the thesis.",
    },
    {
        "requirement_key": "proposal_response_time_measurement",
        "arabic_label": "قياس زمن الاستجابة",
        "technical_label": "Clinical response time measurement",
        "source_document_category": "research_proposal",
        "status": "implemented",
        "related_api_route": "/api/response-tracking",
        "related_frontend_route": "response-time-dashboard",
        "related_export_fields": ["response_delay_minutes", "time_to_alert_minutes", "time_to_response_minutes", "total_response_time_minutes"],
        "notes": "Response tracking preserves alert-to-action intervals.",
    },
    {
        "requirement_key": "proposal_critical_outcomes",
        "arabic_label": "التحويل للطوارئ/العناية والوفيات",
        "technical_label": "ICU transfer, emergency events, and mortality outcomes",
        "source_document_category": "research_proposal",
        "status": "implemented",
        "related_api_route": "/api/outcomes",
        "related_frontend_route": "outcome-tracking",
        "related_export_fields": ["outcome_type", "emergency_admission_datetime", "icu_transfer_datetime", "death_datetime"],
        "notes": "Clinical outcomes and 72-hour validation capture escalation and mortality markers.",
    },
    {
        "requirement_key": "proposal_nurse_training",
        "arabic_label": "اختبار قبلي وبعدي للتمريض",
        "technical_label": "Nurse pre-test and post-test",
        "source_document_category": "research_proposal",
        "status": "implemented",
        "related_api_route": "/api/training/evaluations",
        "related_frontend_route": "nursing-training",
        "related_export_fields": ["training_average_pre_test_percent", "training_average_post_test_percent", "training_average_improvement_percent"],
        "notes": "Training export also provides row-level staff training records.",
    },
    {
        "requirement_key": "proposal_competency_acceptance",
        "arabic_label": "الكفاءة والقبول/الرضا",
        "technical_label": "Competency evaluation and staff satisfaction/acceptance survey",
        "source_document_category": "research_proposal",
        "status": "implemented",
        "related_api_route": "/api/training/summary",
        "related_frontend_route": "nursing-training",
        "related_export_fields": ["training_average_competency_score", "training_competency_pass_rate_percent", "training_average_acceptance_score"],
        "notes": "Acceptance scoring uses a 1-5 survey with low/medium/high levels.",
    },
    {
        "requirement_key": "proposal_research_dataset_export",
        "arabic_label": "مجموعة بيانات البحث والتصدير",
        "technical_label": "Research dataset and export",
        "source_document_category": "research_proposal",
        "status": "implemented",
        "related_api_route": "/api/research/export/csv",
        "related_frontend_route": "export-center",
        "related_export_fields": ["patient_code", "measurement_id", "prediction_classification"],
        "notes": "CSV, XLSX, SPSS codebook, and variable labels are available.",
    },
    {
        "requirement_key": "form_baseline_context",
        "arabic_label": "نموذج خط الأساس والسياق",
        "technical_label": "Baseline patient and dialysis context form",
        "source_document_category": "digital_monitoring_form",
        "status": "implemented",
        "related_api_route": "/api/patients",
        "related_frontend_route": "patient-baseline",
        "related_export_fields": ["vascular_access_type", "vascular_access_location", "vascular_access_placement_date", "target_fluid_removal_ml"],
        "notes": "Baseline and session context fields are persisted and exported.",
    },
    {
        "requirement_key": "form_hd2_mnews_10_variables",
        "arabic_label": "متغيرات HD2-mNEWS العشرة",
        "technical_label": "HD2-mNEWS 10-variable scoring",
        "source_document_category": "digital_monitoring_form",
        "status": "implemented",
        "related_api_route": "/api/hd2-mnews/calculate",
        "related_frontend_route": "vital-signs-entry",
        "related_export_fields": ["respiratory_rate", "spo2", "temperature", "systolic_bp", "pulse_rate", "consciousness_level", "vascular_access_status", "idwg_percent", "ufr", "potassium"],
        "notes": "NEWS2 variables and hemodialysis-specific variables are retained in the dataset.",
    },
    {
        "requirement_key": "form_risk_colors_critical_red",
        "arabic_label": "ألوان الخطورة والتحويل الأحمر التلقائي",
        "technical_label": "Risk colors and automatic red critical trigger",
        "source_document_category": "digital_monitoring_form",
        "status": "implemented",
        "related_api_route": "/api/hd2-mnews/calculate",
        "related_frontend_route": "intradialytic-monitoring",
        "related_export_fields": ["hd2_risk_color", "hd2_mnews_critical_trigger", "hd2_mnews_critical_reasons"],
        "notes": "Critical trigger metadata is exported for traceability.",
    },
    {
        "requirement_key": "form_nursing_protocol",
        "arabic_label": "بروتوكول التمريض حسب اللون",
        "technical_label": "Nursing protocol by risk color",
        "source_document_category": "digital_monitoring_form",
        "status": "implemented",
        "related_api_route": "/api/hd2-mnews/calculate",
        "related_frontend_route": "intradialytic-monitoring",
        "related_export_fields": ["hd2_risk_label_ar", "hd2_reassessment_interval_min", "hd2_reassessment_interval_max", "hd2_protocol_action_summary"],
        "notes": "Protocol guidance appears after HD2 calculation and is exported.",
    },
    {
        "requirement_key": "form_72h_validation",
        "arabic_label": "التحقق السريري بعد 72 ساعة",
        "technical_label": "72-hour clinical outcome validation",
        "source_document_category": "digital_monitoring_form",
        "status": "implemented",
        "related_api_route": "/api/outcome-validations",
        "related_frontend_route": "outcome-tracking",
        "related_export_fields": ["outcome_validation_completed", "outcome_validation_completed_at", "deterioration_occurred"],
        "notes": "Validation is tied to dialysis session traceability.",
    },
    {
        "requirement_key": "form_deterioration_prediction_intervention",
        "arabic_label": "نوع التدهور والتنبؤ والتدخل والنتيجة",
        "technical_label": "Deterioration type, prediction status, interventions, and final result",
        "source_document_category": "digital_monitoring_form",
        "status": "implemented",
        "related_api_route": "/api/outcome-validations",
        "related_frontend_route": "outcome-tracking",
        "related_export_fields": ["deterioration_types_72h", "deterioration_timing_category", "platform_prediction_status", "interventions_72h", "final_result_72h"],
        "notes": "Required validation choices are enforced by the 72-hour workflow.",
    },
    {
        "requirement_key": "form_verification_sources",
        "arabic_label": "مصادر التحقق من البيانات",
        "technical_label": "Data verification source fields",
        "source_document_category": "digital_monitoring_form",
        "status": "implemented",
        "related_api_route": "/api/outcome-validations",
        "related_frontend_route": "outcome-tracking",
        "related_export_fields": ["verification_sources"],
        "notes": "Verification source selection is required for outcome validation.",
    },
]


def build_alignment_audit() -> dict[str, object]:
    counts = Counter(str(row["status"]) for row in ALIGNMENT_REQUIREMENTS)
    total = len(ALIGNMENT_REQUIREMENTS)
    completion = round(((counts.get("implemented", 0) + (counts.get("partial", 0) * 0.5)) / total) * 100, 1) if total else 0.0
    return {
        "summary": {
            "total_requirements": total,
            "completion_percentage": completion,
            "implemented_count": counts.get("implemented", 0),
            "partial_count": counts.get("partial", 0),
            "missing_count": counts.get("missing", 0),
            "out_of_scope_count": counts.get("out_of_scope", 0),
        },
        "rows": ALIGNMENT_REQUIREMENTS,
    }
